### ISSUE TITLE
get newest api info (missing stations)

### ISSUE THREAD

**Issue by zaanposni** [FI18-Trainees/vvspy#12]

**Comment by zaanposni** [comment]
There seems to be a new format: `de:08111:6287`, both versions are usable in the "www3" version of the vvs api.

**Comment by ArPiiX** [comment]
https://www.openvvs.de/dataset/haltestellen/resource/d87d1f01-5c14-4d08-8452-e405a6472ab4

**Comment by ArPiiX** [comment]
https://www.openvvs.de/dataset/haltestellen/resource/d471c25c-e433-41d7-9de7-c33d57401c40

**Comment by zaanposni** [comment]
<b>Problem:</b>
Some stations are missing in the csv.

<b>Solution:</b>
csv is outdated and the format for stationIds is not used anymore.

new ("global") format: `de:08111:6287`
old format: `5006115`

<h3>Note:</h3>
All formats are usable, even mixed.

New formats can be obtained:
- from links above
- the vvs site while making requests with their gui (check the request your browser made)
- vvspy:
	-  `<connection.obj>.origin.id` (on a trip request)
	-  `<connection.obj>.destination.id` (on a trip request)
    - sadly for departure or arrival results the API does not return the new format.


Feel free to open another issue if you have problems regarding the new format.
